let shopItemsData = [
  {
    id: "one",
    name: "Palak paneer",
    price: 129,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "https://img.freepik.com/premium-photo/spinach-soup-with-tofu-spices-black-background_890887-10551.jpg?size=626&ext=jpg&ga=GA1.1.1958931794.1690539217&semt=ais",
  },
  {
    id: "two",
    name: "Veg Biryani",
    price: 249,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "https://img.freepik.com/premium-photo/indian-vegetable-pulav-biryani-made-using-basmati-rice-served-terracotta-bowl-selective-focus_466689-55615.jpg?w=996",
  },
  {
    id: "three",
    name: "Gobi Manchuria",
    price: 199,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "https://img.freepik.com/premium-photo/food-images-any-restaurant_249033-13.jpg?w=900",
  },
 {
    id: "four",
    name: "Veg Salad",
    price: 149,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "https://img.freepik.com/free-photo/vegetables-salad-table_23-2148515515.jpg?w=740&t=st=1694347808~exp=1694348408~hmac=5a033502cd2fcdbfe4c0ff03d0818b8223011737fd5875128fba5bf81095fc00",
  },
  {
    id: "five",
    name: "Cabbage Momos",
    price: 99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "https://im1.dineout.co.in/images/uploads/restaurant/sharpen/1/c/q/p156-149690915759390565dc6b1.jpg?tr=tr:n-large",
  },
  {
    id: "six",
    name: "Potato bhurji",
    price: 150,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "https://im1.dineout.co.in/images/uploads/restaurant/sharpen/5/a/u/p5462-15589556815cebc6a17fe0a.jpg?tr=tr:n-large",
  },
  {
    id: "seven",
    name: "Veg kabab",
    price: 170,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "https://im1.dineout.co.in/images/uploads/restaurant/sharpen/1/q/o/p1896-1500458845596f2f5dc0eec.jpg?tr=tr:n-large",
  },
  {
    id: "eight",
    name: "Curd rice",
    price: 89,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "https://im1.dineout.co.in/images/uploads/restaurant/sharpen/1/t/t/p1896-1500458842596f2f5a93615.jpg?tr=tr:n-large",
  },
  {
    id: "nine",
    name: "Veg Noodles",
    price: 179,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "https://im1.dineout.co.in/images/uploads/restaurant/sharpen/1/n/v/p156-14969091765939057873191.jpg?tr=tr:n-xlarge",
  },
  {
    id: "ten",
    name: "Chappathi Kurma",
    price: 149,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "https://im1.dineout.co.in/images/uploads/restaurant/sharpen/1/j/q/p1896-1500458835596f2f53d862d.jpg?tr=tr:n-large",
  },







  {
    id: "eleven",
    name: "Chicken Dum-Biryani",
    price:299,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "https://img.freepik.com/premium-photo/dum-handi-chicken-biryani-is-prepared-earthen-clay-pot-called-haandi-popular-indian-non-vegetarian-food_466689-52332.jpg?w=996",
  },
  {
    id:"twelve",
    name:"Chicken curry",
    price:179,
    desc:"ldfnbkl esnfejdson erbnwjenwbf",
    img:"https://img.freepik.com/premium-photo/chicken-curry-masala-kerala-style-chicken-curry-using-fried-coconut-traditional-way_527904-1704.jpg?size=626&ext=jpg&ga=GA1.1.1958931794.1690539217&semt=ais",

  },
  {
    id:"thirteen",
    name:"Fish Fry",
    price:229,
    desc:"ldfnbkl esnfejdson erbnwjenwbf",
    img:"https://img.freepik.com/premium-photo/fish-fry-pomfret-fry-garnished-with-purple-cabbage-red-cabbage_527904-1408.jpg?w=996",
  },




  {
    id:"fourteen",
    name:"Prawns curry",
    price:289,
    desc:"ldfnbkl esnfejdson erbnwjenwbf",
    img:"https://img.freepik.com/free-photo/thai-food-tom-yum-kung-river-prawn-spicy-soup_1150-35451.jpg?size=626&ext=jpg&ga=GA1.2.1958931794.1690539217&semt=ais",
  },
  {
    id:"fifteen",
    name:"Egg Biryani",
    price:179,
    desc:"ldfnbkl esnfejdson erbnwjenwbf",
    img:"https://img.freepik.com/premium-photo/chicken-biryani_948735-12129.jpg?w=996",
  },
  {
    id:"sixteen",
    name:"Tandoori Chicken",
    price:199,
    desc:"ldfnbkl esnfejdson erbnwjenwbf",
    img:"https://im1.dineout.co.in/images/uploads/restaurant/sharpen/8/i/b/p853-149087353058dcecbad19d5.jpg?tr=tr:n-large",
  },
  {
    id:"seventeen",
    name:"Non-Veg Thali",
    price:239,
    desc:"ldfnbkl esnfejdson erbnwjenwbf",
    img:"https://th.bing.com/th/id/OIP.GjIwCh89aXCNSbCMbriWkwHaE7?w=280&h=187&c=7&r=0&o=5&dpr=1.3&pid=1.7",
  },
  {
    id:"eightteen",
    name:"Mutton Biryani",
    price:299,
    desc:"ldfnbkl esnfejdson erbnwjenwbf",
    img:"https://th.bing.com/th/id/OIP.wc30SK5S128KKDQni0NmawHaE8?pid=ImgDet&rs=1",
  },
  {
    id:"nineteen",
    name:"Chicken Leg piece",
    price:149,
    desc:"ldfnbkl esnfejdson erbnwjenwbf",
    img:"https://im1.dineout.co.in/images/uploads/restaurant/sharpen/8/h/x/p853-149087353458dcecbecc48f.jpg?tr=tr:n-large",
  },
  {
    id:"twenty",
    name:"Mutton curry",
    price:179,
    desc:"ldfnbkl esnfejdson erbnwjenwbf",
    img:"https://media.istockphoto.com/id/494350327/photo/mutton-curry.jpg?s=612x612&w=0&k=20&c=hVHgWtkKFsQKorKVk30RabALq_09gJR0TsU4P0RZDfg=",
  },
  {
    id:"twentyone",
    name:"Tomato Soup",
    price:99,
    desc:"ldfnbkl esnfejdson erbnwjenwbf",
    img:"https://www.vegrecipesofindia.com/wp-content/uploads/2020/11/tomato-soup-recipe-280x280.jpg",
  },
  {
    id:"twentytwo",
    name:"Rasam Soup",
    price:119,
    desc:"ldfnbkl esnfejdson erbnwjenwbf",
    img:"https://www.vegrecipesofindia.com/wp-content/uploads/2014/02/rasam-recipe-1.jpg",
  },
  {
    id:"twentythree",
    name:"Mushroom Soup",
    price:89,
    desc:"ldfnbkl esnfejdson erbnwjenwbf",
    img:"https://www.vegrecipesofindia.com/wp-content/uploads/2021/11/mushroom-soup-1-280x280.jpg",
  },
  {
    id:"twentyfour",
    name:"Louki Soup",
    price:139,
    desc:"ldfnbkl esnfejdson erbnwjenwbf",
    img:"https://www.vegrecipesofindia.com/wp-content/uploads/2022/12/lauki-soup-280x280.jpg",
  },
  {
    id:"twentyfive",
    name:"Hot and sour Soup",
    price:119,
    desc:"ldfnbkl esnfejdson erbnwjenwbf",
    img:"https://www.vegrecipesofindia.com/wp-content/uploads/2021/07/hot-and-sour-soup-1-280x280.jpg",
  },
  {
    id:"twentysix",
    name:"Cream of Broccoli Soup",
    price:149,
    desc:"ldfnbkl esnfejdson erbnwjenwbf",
    img:"https://www.vegrecipesofindia.com/wp-content/uploads/2021/02/cream-of-broccoli-soup-01-280x280.jpg",
  },
  {
    id:"twentyseven",
    name:"Cream of celeray Soup",
    price:169,
    desc:"ldfnbkl esnfejdson erbnwjenwbf",
    img:"https://www.vegrecipesofindia.com/wp-content/uploads/2014/03/cream-of-celery-soup-recipe-280x280.jpg",
  },
  {
    id:"twentyeigth",
    name:"Carrot Soup",
    price:79,
    desc:"ldfnbkl esnfejdson erbnwjenwbf",
    img:"https://www.vegrecipesofindia.com/wp-content/uploads/2019/12/carrot-soup-2-280x280.jpg",
  },
  {
    id:"twentynine",
    name:"Lemon-coriander soup",
    price:149,
    desc:"ldfnbkl esnfejdson erbnwjenwbf",
    img:"https://www.vegrecipesofindia.com/wp-content/uploads/2019/06/lemon-coriander-soup-280x280.jpg",
  },
  {
    id:"thirty",
    name:"French Onion soup",
    price:189,
    desc:"ldfnbkl esnfejdson erbnwjenwbf",
    img:"https://www.vegrecipesofindia.com/wp-content/uploads/2020/01/french-onion-soup-recipe-280x280.jpg",
  },
  {
    id:"thirtyone",
    name:"Cheese Poppers",
    price:168,
    desc:"kjsdn ",
    img:"https://cdn.tarladalal.com/members/9306/big/big_cheese_poppers-8810.jpg?size=696X905",
  },
  {
    id:"thirtytwo",
    name:"tomato hummus crostini",
    price:179,
    desc:"kjsdn ",
    img:"https://img.taste.com.au/K7tj5itf/w354-h236-cfill-q80/taste/2016/11/tomato-hummus-crostini-25282-1.jpeg",
  },{
    id:"thirtythree",
    name:"sweet saganaki",
    price:189,
    desc:"kjsdn ",
    img:"https://img.taste.com.au/U89Zb03Y/w720-h480-cfill-q80/taste/2021/07/sweet-saganaki_digi_1980x1320-172761-1.jpg",
  },{
    id:"thirtyfour",
    name:"mediterranean pastry",
    price:170,
    desc:"kjsdn ",
    img:"https://img.taste.com.au/E6uN-9fF/w720-h480-cfill-q80/taste/2021/07/tastemagazine2108210427-mediterranean-pastry-172763-1.jpg",
  },{
    id:"thirtyfive",
    name:"bruschetta",
    price:150,
    desc:"kjsdn ",
    img:"https://img.taste.com.au/UALfZjtm/w720-h480-cfill-q80/taste/2016/11/bruschetta-two-ways-38105-1.jpeg",
  },{
    id:"thirtysix",
    name:"Fish and chicken pokra",
    price:180,
    desc:"kjsdn ",
    img:"https://sulthansbiriyani.in/wp-content/uploads/2021/04/Fish-and-chicken-pakora-Delicious-Indian-Non-Veg-Starters.jpg",
  },{
    id:"thirtyseven",
    name:"Chilli Prawns",
    price:179,
    desc:"kjsdn ",
    img:"https://sulthansbiriyani.in/wp-content/uploads/2021/04/Chilli-Prawns-Delicious-Indian-Non-Veg-Starters.jpg",
  },{
    id:"thirtyeight",
    name:"Vegetable Cheese omelet",
    price:169,
    desc:"lksndp",
    img:"https://sulthansbiriyani.in/wp-content/uploads/2021/04/Vegetable-cheese-omelet-Delicious-Indian-Non-Veg-Starters.jpg",
  },
  {
    id:"thirtynine",
    name:"Meatballs",
    price:199,
    desc:"kjsdn ",
    img:"https://sulthansbiriyani.in/wp-content/uploads/2021/04/Meatballs-Delicious-Indian-Non-Veg-Starters.jpg",
  },
  {
    id:"forty",
    name:"Chicken Majestic",
    price:149,
    desc:"kjsdn ",
    img:"https://sulthansbiriyani.in/wp-content/uploads/2021/04/Chicken-Majestic-Delicious-Indian-Non-Veg-Starters.jpg",
  },

  {
    id:"fortyone",
    name:"Floating Island",
    price:99,
    desc:"kjsdn ",
    img:"https://images.immediate.co.uk/production/volatile/sites/30/2020/08/floating-island-3a8b98b.jpg?quality=90&webp=true&resize=375,341",
  },
  {
    id:"fortytwo",
    name:"cherry almond galette",
    price:120,
    desc:"kjsdn ",
    img:"https://images.immediate.co.uk/production/volatile/sites/30/2020/08/cherry-almond-frangipane-galette-07807dc.jpg?quality=90&webp=true&resize=375,341",
  },
  {
    id:"fortythree",
    name:"Blackberry Lemon pool",
    price:125,
    desc:"kjsdn ",
    img:"https://images.immediate.co.uk/production/volatile/sites/30/2020/08/fools-a48cee6.jpg?quality=90&webp=true&resize=375,341",
  },
  {
    id:"fortyfour",
    name:"zesty lemon cake",
    price:150,
    desc:"kjsdn ",
    img:"https://images.immediate.co.uk/production/volatile/sites/30/2020/08/zesty-lemon-cake-1f0e15f.jpg?quality=90&webp=true&resize=375,341",
  },
  {
    id:"fortyfive",
    name:"chocolate malt",
    price:170,
    desc:"kjsdn ",
    img:"https://images.immediate.co.uk/production/volatile/sites/30/2020/08/chocolate-malt-loaf-torte-c002064.jpg?quality=90&webp=true&resize=375,341",
  },
  {
    id:"fortysix",
    name:"nanaimo bars",
    price:149,
    desc:"kjsdn ",
    img:"https://images.immediate.co.uk/production/volatile/sites/30/2020/08/nanaimo-bars-b65516e.jpg?quality=90&webp=true&resize=375,341",
  },
  {
    id:"fortyseven",
    name:"Vannila panna cotta",
    price:179,
    desc:"kjsdn ",
    img:"https://images.immediate.co.uk/production/volatile/sites/30/2020/08/panna-cotta-638cd76.jpg?quality=90&webp=true&resize=375,341",
  },
  {
    id:"fortyeight",
    name:"raspberry brulee",
    price:165,
    desc:"kjsdn ",
    img:"https://images.immediate.co.uk/production/volatile/sites/30/2020/08/raspberry-brulee-4c54f2c.jpg?quality=90&webp=true&resize=375,341",
  },
  {
    id:"fortynine",
    name:"smores dip",
    price:140,
    desc:"kjsdn ",
    img:"https://images.immediate.co.uk/production/volatile/sites/30/2020/08/smores-dip-3f0676b.jpg?quality=90&webp=true&resize=375,341",
  },
  {
    id:"fifty",
    name:"Butterscotch pie",
    price:130,
    desc:"kjsdn ",
    img:"https://images.immediate.co.uk/production/volatile/sites/30/2020/08/butterscotch-pie-82c5643.jpg?quality=90&webp=true&resize=375,341",
  },



  
];